apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "wildlife.preserves.jakubpieta/v1alpha1",
          "kind": "WildlifePreserve",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "wildlife-preserve-operator",
              "app.kubernetes.io/instance": "wildlifepreserve-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "wildlifepreserve",
              "app.kubernetes.io/part-of": "wildlife-preserve-operator"
            },
            "name": "wildlifepreserve-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-10-05T13:04:43Z"
    operators.operatorframework.io/builder: operator-sdk-v1.31.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: wildlife-preserve-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: WildlifePreserve is the Schema for the wildlife-preserves API
      displayName: Wildlife Preserve
      kind: WildlifePreserve
      name: wildlifepreserves.wildlife.preserves.jakubpieta
      version: v1alpha1
  description: Wildlife Preserve Operator
  displayName: Wildlife Preserve Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - wildlife.preserves.jakubpieta
          resources:
          - persistentvolumeclaims
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
        - apiGroups:
          - wildlife.preserves.jakubpieta
          resources:
          - persistentvolumes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
        - apiGroups:
          - wildlife.preserves.jakubpieta
          resources:
          - wildlifepreserves
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - wildlife.preserves.jakubpieta
          resources:
          - wildlifepreserves/finalizers
          verbs:
          - update
        - apiGroups:
          - wildlife.preserves.jakubpieta
          resources:
          - wildlifepreserves/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: wildlife-preserve-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: wildlife-preserve-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: wildlife-preserve-operator
          control-plane: controller-manager
        name: wildlife-preserve-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: jakubpieta/wildlife-preserve-operator:v0.0.2
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: wildlife-preserve-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: wildlife-preserve-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - test
  links:
  - name: Wildlife Preserve Operator
    url: https://wildlife-preserve-operator.domain
  maturity: alpha
  provider:
    name: Jakub Pięta
  version: 0.0.1
