# permissions for end users to edit wildlifepreserves.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: wildlifepreserve-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: wildlife-preserve-operator
    app.kubernetes.io/part-of: wildlife-preserve-operator
    app.kubernetes.io/managed-by: kustomize
  name: wildlifepreserve-editor-role
rules:
- apiGroups:
  - wildlife.preserves.my.domain
  resources:
  - wildlifepreserves
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wildlife.preserves.my.domain
  resources:
  - wildlifepreserves/status
  verbs:
  - get
