apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: wildlife-preserve-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: WildlifePreserve is the Schema for the wildlife-preserves API
      displayName: Wildlife Preserve
      kind: WildlifePreserve
      name: wildlifepreserves.wildlife.preserves.jakubpieta
      version: v1alpha1
  description: Wildlife Preserve Operator
  displayName: Wildlife Preserve Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - test
  links:
  - name: Wildlife Preserve Operator
    url: https://wildlife-preserve-operator.domain
  maturity: alpha
  provider:
    name: Jakub Pięta
  version: 0.0.0
