apiVersion: wildlife.preserves.my.domain/v1alpha1
kind: WildlifePreserve
metadata:
  labels:
    app.kubernetes.io/name: wildlifepreserve
    app.kubernetes.io/instance: wildlifepreserve-sample
    app.kubernetes.io/part-of: wildlife-preserve-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: wildlife-preserve-operator
  name: wildlifepreserve-sample
spec:
  # TODO(user): Add fields here
